# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory
set_property part xc7vx485tffg1761-2 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
read_verilog -sv {
  C:/work/psx_synthesis/hdmi_test_v5/hdmi_test_v5.srcs/sources_1/imports/hdmi/video.sv
  C:/work/psx_synthesis/hdmi_test_v5/hdmi_test_v5.srcs/sources_1/imports/hdmi/spdif.sv
  C:/work/psx_synthesis/hdmi_test_v5/hdmi_test_v5.srcs/sources_1/imports/hdmi/iic_config.sv
  C:/work/psx_synthesis/hdmi_test_v5/hdmi_test_v5.srcs/sources_1/imports/hdmi/hdmi.sv
  C:/work/psx_synthesis/hdmi_test_v5/hdmi_test_v5.srcs/sources_1/imports/hdmi/feed.sv
  C:/work/psx_synthesis/hdmi_test_v5/hdmi_test_v5.srcs/sources_1/imports/hdmi/top_test.sv
}
read_verilog {
  C:/work/psx_synthesis/hdmi_test_v5/hdmi_test_v5.srcs/sources_1/imports/chipscope_1/hdmi_icon.v
  C:/work/psx_synthesis/hdmi_test_v5/hdmi_test_v5.srcs/sources_1/imports/chipscope_1/chipscope_ila.v
}
read_edif C:/work/psx_synthesis/hdmi_test_v5/hdmi_test_v5.srcs/sources_1/imports/chipscope_1/hdmi_icon.ngc
read_edif C:/work/psx_synthesis/hdmi_test_v5/hdmi_test_v5.srcs/sources_1/imports/chipscope_1/chipscope_ila.ngc
read_xdc C:/work/psx_synthesis/hdmi_test_v5/hdmi_test_v5.srcs/constrs_1/new/top_test.xdc
set_property used_in_implementation false [get_files C:/work/psx_synthesis/hdmi_test_v5/hdmi_test_v5.srcs/constrs_1/new/top_test.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/work/psx_synthesis/hdmi_test_v5/hdmi_test_v5.data/wt [current_project]
set_property parent.project_dir C:/work/psx_synthesis/hdmi_test_v5 [current_project]
synth_design -top top_test -part xc7vx485tffg1761-2
write_checkpoint top_test.dcp
report_utilization -file top_test_utilization_synth.rpt
