# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
create_project -in_memory -part xc7vx485tffg1761-2
set_property board xilinx.com:virtex7:vc707:a [current_project]
set_param project.compositeFile.enableAutoGeneration 0
read_verilog -sv {
  /work/team_psx/labs/lab2_sound/hdmi_test_v5/hdmi_test_v5.srcs/sources_1/imports/hdmi/video.sv
  /work/team_psx/labs/lab2_sound/hdmi_test_v5/hdmi_test_v5.srcs/sources_1/imports/hdmi/spdif.sv
  /work/team_psx/labs/lab2_sound/hdmi_test_v5/hdmi_test_v5.srcs/sources_1/imports/hdmi/iic_config.sv
  /work/team_psx/labs/lab2_sound/hdmi_test_v5/hdmi_test_v5.srcs/sources_1/imports/hdmi/hdmi.sv
  /work/team_psx/labs/lab2_sound/hdmi_test_v5/hdmi_test_v5.srcs/sources_1/imports/hdmi/feed.sv
  /work/team_psx/labs/lab2_sound/hdmi_test_v5/hdmi_test_v5.srcs/sources_1/imports/hdmi/top_test.sv
}
read_verilog {
  /work/team_psx/labs/lab2_sound/hdmi_test_v5/hdmi_test_v5.srcs/sources_1/imports/chipscope_1/hdmi_icon.v
  /work/team_psx/labs/lab2_sound/hdmi_test_v5/hdmi_test_v5.srcs/sources_1/imports/chipscope_1/chipscope_ila.v
}
read_edif /work/team_psx/labs/lab2_sound/hdmi_test_v5/hdmi_test_v5.srcs/sources_1/imports/chipscope_1/hdmi_icon.ngc
read_edif /work/team_psx/labs/lab2_sound/hdmi_test_v5/hdmi_test_v5.srcs/sources_1/imports/chipscope_1/chipscope_ila.ngc
read_xdc /work/team_psx/labs/lab2_sound/hdmi_test_v5/hdmi_test_v5.srcs/constrs_1/new/top_test.xdc
set_property used_in_implementation false [get_files /work/team_psx/labs/lab2_sound/hdmi_test_v5/hdmi_test_v5.srcs/constrs_1/new/top_test.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /work/team_psx/labs/lab2_sound/hdmi_test_v5/hdmi_test_v5.data/wt [current_project]
set_property parent.project_dir /work/team_psx/labs/lab2_sound/hdmi_test_v5 [current_project]
synth_design -top top_test -part xc7vx485tffg1761-2
write_checkpoint top_test.dcp
report_utilization -file top_test_utilization_synth.rpt -pb top_test_utilization_synth.pb
