
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 2013.2 EDK_P.68d
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xaxidma.h"

/*
* The configuration table for devices
*/

XAxiDma_Config XAxiDma_ConfigTable[] =
{
	{
		XPAR_AXI_DMA_0_DEVICE_ID,
		XPAR_AXI_DMA_0_BASEADDR,
		XPAR_AXI_DMA_0_SG_INCLUDE_STSCNTRL_STRM,
		XPAR_AXI_DMA_0_INCLUDE_MM2S,
		XPAR_AXI_DMA_0_INCLUDE_MM2S_DRE,
		XPAR_AXI_DMA_0_M_AXIS_MM2S_TDATA_WIDTH,
		XPAR_AXI_DMA_0_INCLUDE_S2MM,
		XPAR_AXI_DMA_0_INCLUDE_S2MM_DRE,
		XPAR_AXI_DMA_0_S_AXIS_S2MM_TDATA_WIDTH,
		XPAR_AXI_DMA_0_INCLUDE_SG,
		XPAR_AXI_DMA_0_NUM_MM2S_CHANNELS,
		XPAR_AXI_DMA_0_NUM_S2MM_CHANNELS
	}
};


